### ISSUE TITLE
API down / changed?

### ISSUE THREAD

**Issue by radokristof** [balassy/MMM-Bubi#3]
The module doesn't seem to appear for me.

Also the provided link to nextbike in the README stopped working...

**Comment by balassy** [comment]
It seems their service is failing, it returns 503 even on the molbubi.hu page:

![bubi-503](https://user-images.githubusercontent.com/1872777/67927161-31d35b00-fbb8-11e9-8d08-d4aaa8a2ba8c.png)

Even the map on their homepage does not show the Bubi stations, I guess their latest maintenance was not that successful:

![bubi-map](https://user-images.githubusercontent.com/1872777/67927191-46afee80-fbb8-11e9-9312-5bb7cd198583.png)

**Comment by radokristof** [comment]
Yes I also saw that, the only thing I didn't know that, when this happened... Hope they will fix it, and will be the same API as before...

**Comment by radokristof** [comment]
The API is back and works as before. Closing this issue.
